name: "@ubiquity-os-marketplace/daemon-xp"
description: "Experience points and rewards daemon."

inputs:
  stateId:
    description: "State Id"
    required: true
  eventName:
    description: "Event Name"
    required: true
  eventPayload:
    description: "Event Payload"
    required: true
  settings:
    description: "Settings"
    required: true
  authToken:
    description: "Auth Token"
    required: true
  ref:
    description: "Ref"
    required: false
  signature:
    description: "The kernel signature"
    required: true
  command:
    description: "Command from the Kernel"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: execute directive
      shell: bash
      run: node ./dist/index.js
      env:
        PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL || 'info' }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
